apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostreport
  labels:
    app: lostreport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostreport
  template:
    metadata:
      labels:
        app: lostreport
    spec:
      containers:
        - name: lostreport
          image: "username/lostreport:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
